---
- name: Install k3s Master1
  hosts: master1
  become: yes
  tasks:
    - name: Download and install k3s master1
      shell: |
        curl -sfL https://get.k3s.io | sh -s - server --cluster-init
      args:
        creates: /etc/rancher/k3s/k3s.yaml

    - name: Get k3s master node token
      command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false

    - name: Get master node IP
      shell: hostname -I | awk '{print $1}'
      register: master_ip
      changed_when: false

    - name: Set token and master IP as facts
      set_fact:
        k3s_token: "{{ k3s_token.stdout }}"
        master_ip: "{{ master_ip.stdout }}"


- name: Install k3s Master2
  hosts: master2
  become: yes
  tasks:
    - name: Download and install k3s master2
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL="https://{{ hostvars['master1']['master_ip'] }}:6443" K3S_TOKEN="{{ hostvars['master1']['k3s_token'] }}" sh -s - server
      args:
        creates: /etc/rancher/k3s/k3s.yaml

- name: Install k3s Master3
  hosts: master3
  become: yes
  tasks:
    - name: Download and install k3s master3
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL="https://{{ hostvars['master1']['master_ip'] }}:6443" K3S_TOKEN="{{ hostvars['master1']['k3s_token'] }}" sh -s - server
      args:
        creates: /etc/rancher/k3s/k3s.yaml